/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

MERGE INTO Service AS Target 
USING (VALUES 
        (1, 'Belconnen Community Service', 'At Belconnen Community Service we have so many things to do, services and programs for the whole community. From babies and toddlers to people over 65, parents, people living with mental illness or disability, Aboriginal and Torres Strait Islander specific programs and youth services for children at school and young people between 12 and 25.', 62640200, '26 Chandler Street, Belconnen ACT 2616', -35.230168, 149.07014, 'bcs@bcsact.com.au', 'Monday to Friday, 9AM to 5PM', 0, 0, 0, 1, 0, 1, 1, 'Belconnen', 'Parking, Toilets, Ramps', null, null, null, null, null, null, 'https://www.bcsact.com.au/'), 
        (2, 'Bit Bent - Gender Diverse Support', 'Bit Bent is a social support group for same sex attracted and sex and gender diverse young people in the Canberra region.  The Belconnen Bit Bent group is held every Monday from 6pm to 8pm during school terms and is facilitated by two Youth Engagement team members and an LGBTIQ+ community volunteer.', 62640200, 'Belconnen Youth Centre, Corner of Chandler Street and Swanson Court, Belconnen', -35.230168, 149.07014, 'bcs@bcsact.com.au', 'Monday evenings, 6PM to 8PM, during school terms', 0, 1, 0, 0, 0, 1, 1, 'Belconnen', null, 'Anyone', null, 12, 25, 'No fee', null, 'https://www.bcsact.com.au/programs-and-services/bit-bent-lgtbiq-social-group-youth-services/'),
		(3, 'Headspace Canberra', 'headspace Canberra is a free or low cost, confidential service where 12 to 25 years old can access mental health professionals. We offer a range of supports for young people worried about their drug and alcohol use, mental, physical or sexual wellbeing.', 51099700, '1-3, 1 Torrens Street, Braddon, 2612, Australian Capital Territory', -35.275761, 149.133438, 'hs.canberra@marathonhealth.com.au', 'Monday: 9:00am - 5:00pm 
Tuesday: 9:00am - 7:00pm 
Wednesday: 11:00am - 5:00pm 
Thursday: 9:00am - 7:00pm 
Friday: 9:00am - 5:00pm 
Saturday: Closed 
Sunday: Closed', 0, 0, 0, 0, 0, 1, 1, 'Civic', 'Parking, Ramps, Wheelchair Access, Lift', 'Anyone', null, 12, 25, 'Contact us for details', null,'https://headspace.org.au/headspace-centres/headspace-canberra/'),
		(4, 'Barnados Canberra','Barnardos Australia''s Canberra Centre offers family support, out-of-home care and supported accommodation services for disadvantaged children, adolescents and their families in the ACT.', 62289500, '2 Atherton Street, Downer, ACT, 2602', -35.243746, 149.142245, 'None Provided', 'Monday to Friday, 8AM to 6PM', 1, 0, 0, 0, 0, 0, 1, 'Civic', null, 'Anyone', 'Contact us for details', null, null, 'No fee', null,'https://www.barnardos.org.au/our-centres/canberra/'),
		(5,'Legal Aid ACT - Youth Law Centre', 'The Youth Law Centre (YLC) is Canberra’s free legal service dedicated to young people aged 12-25.
We provide free and confidential legal advice in person, over the phone and by email.', 61735410 ,'2 Allsop Street, Canberra, right across from ANU', -35.278411, 149.124878, 'ylc@legalaidact.org.au', 'None listed', 0, 0, 0, 0, 1, 0, 0, 'Civic', 'Wheelchair access, Toilets', 'Anyone', null, 12, 25, 'No fee', null, 'http://www.legalaidact.org.au/'),
		(6, 'Multi-Cultural Youth Services', 'Outreach and drop in service assisting young people aged 12-21yrs, who have a culturally and linguistically diverse background (migrants and refugees) to overcome barriers to obtaining work, accommodation, education or training. Provides one on one support that is flexible and responsive, regular recreational activities for social connection, drop-in: 3-6pm Wed-Thu, 3-7pm Fri.', 61004611, '180 London Circuit, Canberra Australian Capital Territory 2602', -35.28028, 149.130915, 'None Provided', 'Monday to Friday, 10AM to 5PM', 0, 0, 0, 0, 0, 1, 1, 'Civic', 'Toilets, Lift, Wheelchair access', 'Anyone', null, 12, 21, 'No fee', 'Dinka, Karen, Burmese, Thai, Swahiti, Arabic', 'http://www.mys.org.au/'),
		(7, 'Anglicare Club 12 25', 'Provides a range of youth specific programs, activities and support (for age 12-25). Drop in provides a safe place to seek assistance, have a meal and a cuppa, catch up with friends, use the internet and participate in activities/programs. Offers case management support and runs programs in schools and with community organisations. Also provides emergency food relief. Call during normal business hours to speak to a youth worker.', 62322488,'Club 1225 Lvl 2, Cnr Scotts Csg & Cooyong St, Canberra City ACT 2601', -35.277106, 149.134528, 'None Provided', 'Tuesday to Friday, 3PM to 6PM', 0, 1, 0, 0, 0, 0,1, 'Civic', 'Toilets, Lift, Wheelchair access', 'Anyone', null, 12, 25, 'No fee', null, 'https://www.anglicare.com.au/services/youth-family/'),
		(8, 'Anglicare - Junction Youth Health Service', 'Provides free primary health care and support services for people aged 12-25yrs and their dependents, with a particular focus on young people who are homeless or otherwise at risk. Provides care and support to young people in relation to all aspects of their health and well being.
Services include GPs, nurses, antenatal care, smoking cessation support, counselling, case management, youth work support and outreach in schools, other services and to individuals. The Junction also provides information, education, referral and advocacy.', 62322423,'Club 1225 Lvl 2, Cnr Scotts Csg & Cooyong St, Canberra City ACT 2601', -35.277106, 149.134528, 'None Provided', 'Monday to Friday, 930AM to 5PM', 0, 0, 0, 0, 0, 0, 1, 'Civic', 'Toilets, Lift, Wheelchair access', 'Anyone', null, 12, 25, 'No fee', null, 'https://www.anglicare.com.au/services/youth-family/'),
		(9, 'Anglicare - Youth Education Program', 'The Youth Education Program (YEP) is one of a suite of services that Anglicare ACT delivers that assists young people and their families through challenging times.
YEP is a flexible learning option for young people aged 14-19 who have disengaged from mainstream education. YEP provides structured, individualised case management to assist young people towards further education, or preparation for work. The case management approach incorporates pathway and learning plans to support young people reach their educational goals. YEP currently have two case managers to assist young people with their individualised plan and support them reach their full potential.
Along with enhancing essential literacy and numeracy skills, YEP provides other learning experiences to promote personal resilience and problem solving skills. YEP operates two sessions per day, morning and afternoon session, to provide students with more flexibility and independence.  At YEP, it is our goal that, the young people, will have an increased ability to participate in the community through employment, training, recreation, artistic expression and/or volunteering.', 62322488, 'Club 1225 Lvl 2, Cnr Scotts Csg & Cooyong St, Canberra City ACT 2601', -35.277106, 149.134528, 'None Provided','Monday to Friday, 9:30AM to 3:30PM', 0, 0, 0, 0, 0, 0, 1, 'Civic', 'Toilets, Lift, Wheelchair access', 'Anyone', null, 14, null, 'No fee', null, 'https://www.anglicare.com.au/services/youth-family/education/'),
		(10, 'The Pantry - Mercy Australia', 'Our vision for the Pantry continues with the same values: to endeavor to provide low cost food and household goods to the disadvantaged and vulnerable in our area whilst providing them a place of hospitality, love and care to enjoy friendship and acceptance', 0419017552,'76 Federal Highway, Watson ACT 2602', -35.226416, 149.160323, 'None Provided', 'Thurdays 10AM to 3PM', 0, 1, 0, 0, 0, 0, 0, 'Civic', null, 'Anyone', null, null, null, 'Contribution Fee', null, 'https://www.ywamcanberra.org/'),
		(11, 'Mary Mead KAYAKS program', 'Marymead''s Kayaks Program helps children and young people aged 8 to 18 years from separated families adjust to life after separation. Through drawing, collage, stories, puppetry, clay, words and play, it assists them to understand why parents separate, tell their story, express their needs so that others can understand them better, find ways to deal with emotions, connect with others, and build coping skills for life.', 1800427920, 'Rheinberger Centre, Corner Weston and Loch Streets, Yarralumla ACT 2600', -35.309709, 149.10427, 'programs@marymead.org.au', 'Monday to Friday 9AM to 5PM', 0, 0, 0, 1, 0, 0, 1, 'Woden', 'Wheelchair access, Parking', 'Anyone', null, 8, 18, 'Contact us for details', null, 'http://www.marymead.org.au/services/kids-and-youth-are-kool-post-separation-kayaks'),
		(12, 'YouthCare Canberra', 'YouthCARE Canberra provides outreach support services to young people (12 to 25 years) at risk, including those who face homelessness and violence.', 62487771, '45 Constitution Avenue, Reid ACT 2612', -35.288003, 149.140181, 'hello@rawpotential.com.au', 'None listed', 0, 0, 0, 0, 0, 0, 1, 'Civic', 'Wheelchair access', 'Anyone', null, 12, 25, 'No fee', null, 'https://www.stjohnscare.org.au/youthcare-canberra'),
		(13, 'Youth Step Up Step Down Program', 'Recovery-focused residential mental health program for young people aged 18-24yrs 11mths experiencing mental illness. The program supports up to 6 people at any time and is suitable for people for whom a short stay may prevent the need for a hospital admission, or people who have experienced an acute episode but no longer require psychiatric in-patient care but require a further period of recovery in a supported environment to successfully transition back into the community.', 62968000,'Callam Offices, 50 Easty Street, Phillip ACT 2606', -35.342942, 149.088914, 'enquiries@wellways.org', 'Monday to Friday 9AM to 5PM', 0, 0, 0, 0, 0, 0, 1,'Woden', 'Wheelchair access', 'Anyone', 'Clinical Manager or Clinician', 18, 24, 'Contact us for details', 'Italian, Tibetan, French, Dutch, Amharic, Hindi, Korean', 'https://www.wellways.org/our-services/youth-step-step-down'),
		(14, 'Woden Community Service', 'Woden Community Service is a for-purpose organisation that provides services to children, families, young people and seniors including disability, housing and mental health services.', 62822644, '26 CORINNA Street, Phillip Australian Capital Territory 2606', -35.345286, 149.083472, 'info@wcs.org.au', 'Monday to Friday 9AM to 5PM', 0, 1, 0, 1, 0, 1, 1, 'Woden','Parking, Toilets, Wheelchair access', null, null, null, null, null, null, 'https://www.wcs.org.au/'),
		(15, 'CatholicCare - Youth Housing Support Service', 'Is your use of alcohol, tobacco and / or other drugs starting to affect your motivation, school work, relationships with your parents, family and friends?
Would you like to talk to someone who understands in a safe, comfortable and non-judgemental environment?
The CatholicCare Reaching Out Program provides free alcohol and drug counselling to young people aged 13-18 years. Our Counselling sessions are provided through outreach, which means rather than having to come to us, we can meet you in a place where you feel most comfortable; be it your school, community centre, or work place.
Our counsellors understand that being lectured about Drugs and Alcohol is not necessarily what you need. The Reaching Out Program is an opportunity to talk with someone who is qualified to help you figure out what works best for you.
We also offer support for families and friends of people impacted by alcohol and other drugs.', 61637600, '57 Hicks Street, Red Hill ACT 2603', -35.339137, 149.129494, 'HSS@catholiccare.cg.org.au', 'None Provided', 0, 0, 0, 0, 0, 0, 1, 'Woden', null, 'Approved service users', 'State/ Territory Government', 15, 25, 'No fee', null, 'https://catholiccare.cg.org.au/services/youth-housing-support-service/'),
		(16, 'catholicCare - Youth Reaching Out', 'The Youth Housing Support Service is an Outreach Program that provides support to young people in the Canberra region who are aged 15-25 years, who are homeless or at risk of homelessness. The Programs provides Case Management support to address identified goals and barriers to finding safe stable and sustainable housing, including information, referral advocacy and linkages to various health and welfare services.  The Program is funded by the Community Services Directorate of the ACT.', 61637695,'57 Hicks Street, Red Hill ACT 2603', -35.339137, 149.129494, 'info@catholiccare.cg.org.au', 'Tuesday to Saturday 9AM to 5PM', 0, 0, 0, 1, 0, 0, 1, 'Woden', null, 'Anyone', null, 13, 18, 'No fee', null, 'https://catholiccare.cg.org.au/services/youth-reaching-out-program/'),
		(17, 'Queer Youth Together QYOUT', 'Queer Youth Together (pronounced QyouT) is a program for LGBTIQ+ young people that will provide a safe place, activities, networking, resources, and just good fun.', 0438018799, 'Diversity Hub, 8 Laidlaw Place, Kambah ACT 2902', -35.390708, 149.061975, 'None Provided', 'Every Second Wednesday, between 530PM and 730PM', 0, 0, 0, 0, 0, 1, 0, 'Tuggeranong', 'Parking, Toilets, Ramp', 'Anyone', null, null, null, 'No fee', null, 'https://diversityact.org.au/queer-youth-together-qyt/'),
		(18, 'Canberra PCYC', 'Provides youth and community with recreational and sporting facilities, case management and programs to engage vulnerable youth in order to minimise their susceptibility to crime. Offers strength and conditioning training and organises Blue Light Discos for primary school aged children. Examples of activities: Aikido; Jishu Kan; Kokusai Jujutsu Ryu; Kyokushin Karate; Shobu Kai Karate; Rockwall; Tots Tumbling; Weight Lifting; Judo; Wrestling; Dancing; Soccer; Cricket; Boxing; Parkour and other sports. Parenting courses also available.', 62961292, '17 Grattan Court, Wanniassa ACT 2903', -35.402481, 149.098201, 'erindale@pcyc.net.au', 'Monday to Friday 9AM to MIDDAY and 4PM to 8PM', 0, 0, 0, 0, 0, 0, 1, 'Tuggeranong', 'Parking, Toilets', 'Anyone', null, null, null, 'Contact us for details', null,'https://www.pcyc.net.au/'),
		(19, 'Food Fair', 'Anglicare’s Food Fair initiative is a community pantry that will help vulnerable families stretch their dollar further. Food Fair is run out of Anglicare’s Queanbeyan-based recycling store, Bargain Hunter, and is stocked with a wide range of grocery items at discounted prices.', 62329272, '114-120 Monaro Street, Queanbeyan NSW 2620', -35.35303, 149.235047, 'food.fair@anglicare.com.au', 'Monday to Friday 930AM to 2PM ', 0, 1, 0, 0, 0, 0, 0, 'Fyshwick', 'Wheelchair Access', null, null, null, null, 'Contribution Fee', null, 'https://www.anglicare.com.au/'),
		(20, 'Oasis Youth Services', 'Provides emergency accommodation and Outreach case management support to homeless young people aged 16-25yrs. Regionally based emergency accommodation services across the ACT.',62920894,'7B Hester Place, Chisholm ACT 2905', -35.420056, 149.128842, 'None Provided', 'Every day 24/7', 0, 1, 0, 0, 0, 0, 0, 'Tuggeranong', null, null, null, null, null, 'No fee', null, 'https://www.salvationarmy.org.au/oasis/'),
		(21, 'Crisis Youth Refuge Queenbeyan', 'Provides emergency and short-term accommodation and support to young people aged from 15 -17 years inclusive (other supports to people 15-24 yrs) that are homeless.', 62329717, '17 Kathleen Street, Queanbeyan NSW 2620', -35.361945, 149.235923, 'syfs@syfs.org.au', 'Every day', 0, 1, 0, 0, 0, 0, 0, 'Fyshwick', null, null, null, null, null, null, null, 'http://www.syfs.org.au/syfs-services/supported-accommodation-and-housing/crisis-youth-refuge-queanbeyan/'),
		(22, 'Common Ground Canberra', 'Low cost supportive housing initiative focused on providing quality tenant outcomes for people who are experiencing chronic homelessness or are low income earners. Provides high quality housing and facilitates the provision of a supported and inclusive community for its tenants. Services include onsite case management, peer support, life skills, education and employment options and social, and well being programs.', 62572255, 'The Valley Av, Gungahlin ACT 2912', -35.187291, 149.132911, 'Fiona.Cameron@northside.asn.au', 'Monday to Friday, 9AM to 5PM', 0, 1, 0, 0, 0, 1, 0, 'Gungahlin', null, 'Anyone', null, null, null, 'No fee', null, 'https://www.commongroundcanberra.org.au/'),
		(23, 'Street-Law', 'Outreach legal service for people who are homeless or at risk of homelessness. Provides advice and assistance on a broad range of legal issues. Operates local advice centres at several hosting agencies across Canberra. Help is also available to clients living in Queanbeyan. All services are free.', 1800787529, 'Lvl 1, 21 Barry Drive, Turner ACT 2612', -35.274793, 149.126308, 'info@streetlaw.org.au', 'Monday to Friday, 9AM to 5PM', 0, 0, 0, 0,1, 0, 0, 'Civic', 'Parking, Ramps', 'Anyone', null, null, null, 'No fee', 'Some available, contact us for more details', 'https://www.canberracommunitylaw.org.au/street-law.html'),
		(24, 'Early Morning Centre', 'Provides a free breakfast and drop in referral service for people who are homeless or at risk of homelessness. Referral service assists people in finding services that are right for their needs.
Practical and emotional support provided for people experiencing housing crisis or housing insecurity, including access to shower, laundry, computer. Breakfast 7:30-8:30am weekdays except public holidays.', 62475041, 'Pilgrim House, 69 Northbourne Avenue, Canberra ACT 2601', -35.276483, 149.129038, 'emc@canberracityuca.org.au','Monday to Friday, 7:30AM to 11:30AM', 0,1, 0, 0, 0, 0, 1, 'Civic', 'Wheelchair Access', 'Anyone', null, null, null, 'No fee', null, 'https://www.canberracityuca.org.au/html/early_morning_centre.html'),
		(25, 'Pets in the Park', 'Pets In The Park is a free pet clinic provided for the homeless or those at risk of homelessness who have animal companions.
The clinic is run by volunteer vets and vet nurses who believe that everybody who loves their pet deserves access to veterinary care.
It is held the first Sunday of every month 2-4pm, 1-3pm over winter, at the Early Morning Centre plaza area around the back.
Unfortunately we have very limited resources and we are unable to help everyone. For this reason we need to ensure that everyone who comes qualifies for our support.', 62475041, 'Civic Early Morning Centre, 69 Northbourne Avenue, Canberra ACT 2601', -35.275929, 149.12916, 'emc@canberracityuca.org.au', 'Not listed', 0, 0, 0, 0, 0, 0, 1, 'Civic', null, 'Approved service users', 'An Organisation', null, null, 'No fee ', null, 'www.petsinthepark.org.au/'),
		(26, 'Conflict Resolution Service Family Tree House Program', 'Assists young people aged between 13 and 20, and their families, who are homeless or at risk of homelessness due to ongoing family conflict. The program works from a conflict resolution framework to assist individuals to prevent, manage, and resolve arguments in the home through practical strategies and coaching.', 61890590, 'Lvl 2 & 3, Griffin Centre, 20 Genge St, Canberra ACT 2601', -35.276922, 149.13252, 'admin@crs.org.au', 'Monday to Friday 9AM to 5PM', 0, 0, 0, 1, 0, 0, 1, 'Civic', 'Parking, Toilets', 'Anyone', null, null, null, 'No fee', null, 'https://crs.org.au/about-crs/contact-us/'),
		(27, 'Safe Shelter ACT - st Columba''s Braddon', 'Emergency overnight (7.00 pm to 7.00 am) shelter for homeless men as part of the Safe Shelter ACT network between 28 April and 26 October 2019. All Saints Ainslie opens Sunday & Monday nights only. St Columba''s Braddon opens Tuesday, Wednesday & Thursday nights. Salvation Army Canberra City Corps opens Friday & Saturday nights. No bookings required. No meals but hot drinks provided. Swags provided if required. Doors locked and lights out at 10.00 pm.', 62489609, '10 Fawkner Street, Braddon ACT 2612', -35.271682, 149.13617, 'safeshelteract@gmail.com', 'Tuesday to Thursday, 7PM to 7AM (Dusk til Dawn)', 1, 0, 0, 0, 0, 0, 0, 'Civic', 'Wheelchair Access, Toilets', 'Males only', null, null, null, 'No fee', null, 'https://www.safeshelteract.org.au/about-safe-shelter'),
		(28, 'Saint Vincent De Paul - Family Services', 'Provides support and outreach to families in the Canberra region who are homeless or at risk of homelessness. 
This service is available to any family that is currently or at risk of homelessness. A family is defined as anyone, single mother, father or couple with at least one dependent child in majority care. The main focus is providing accommodation and support to families with an emphasis on the safety, well-being and development of children.', 62822722, '15 Denison St, Deakin ACT 2600', -35.315416, 149.096979, 'info@svdp-cg.org.au', 'Not listed', 1, 0, 0, 1, 0, 0, 0,'Woden', 'Wheelchair Access', 'Anyone', null, null, null, 'Contact us for details', null, 'https://www.vinnies.org.au/page/Find_Help/ACT/Health_and_wellbeing/Family_Services/'),
		(29, 'ACT Street Soccer', 'The heart of Street Soccer is weekly training sessions held across Australia. Participants get together in a safe and non-threatening environment, allowing them to get fit, make new friends and seek support and advice.
Our support staff also work closely with players, linking them to services that address issues including homelessness, substance abuse, family breakdown and mental illness.
Through the program, we engage people who in many cases have given up on counselling and traditional support systems and services. Street Soccer puts the person at the centre of the solution and provides them with the support and tools necessary to make positive changes to their lives.', 0418233959, 'Reid Oval, Elimatta Street Reid, Canberra ACT 2612', -35.281382, 149.144601, 'thebigissue@wcs.org.au', '2PM to 4PM Wednesdays', 0, 1, 0, 0, 0, 1, 1, 'Civic', null, 'Anyone', null, 16, null, 'No fee', null, 'https://www.thebigissue.org.au/community-street-soccer/where-we-play/'),
		(30, 'The Ted Noffs Foundation', 'The primary focus of Noffs services is socially disadvantaged and disconnected young people and those from the Indigenous community as well as those from culturally and linguistically diverse backgrounds. Our particular expertise is in the treatment of young people with drug and alcohol problems and in particular those with comorbid mental health issues. While focussed on young people, Noffs involves the entire community by organising and promoting events to create shared experiences, open pathways for communication and enhance the sense of social inclusion.', 61232400, '350 Antill Street, Watson ACT 2602', -35.238293, 149.167199, 'team@noffs.org.au', 'Not listed', 0, 0, 0, 0, 0, 0, 1, 'Civic', null, 'Anyone', 'Contact us for details', null, null, 'No fee', null, 'https://noffs.org.au/'),
		(31, 'The Big Issue', 'Provides people who are marginalised or disadvantaged with the opportunity to earn an income and be actively included in society.
Vendors include people experiencing homelessness, mental illness, long-term unemployment, intellectual or physical disability or social isolation.
Vendors run their own business selling The Big Issue magazine in public places around Canberra, keeping half the proceeds from every magazine sold.', 0448476184, 'Woden Community Service, 26 Corinna Street, Phillip ACT 2606', -35.34513, 149.083476, 'thebigissue@wcs.org.au', 'Not listed', 0, 0, 1, 0, 0, 0, 1, 'Woden', 'Wheelchair Access', 'Anyone', null, null, null, 'No fee', null, 'https://www.thebigissue.org.au/'),
		(32, 'CatholicCare Reconnect', 'Reconnect is a voluntary early intervention program for young people aged between 12-18 years who are at risk of homelessness or are already homeless and living, working or studying in the ACT.
The program aims to help young people achieve family reconciliation and improve their level of engagement with work, education, training and the community.
Reconnect provides opportunities, choices and support for young people and works towards reconnecting young people with parents, carers or significant others to achieve family reconciliation, wherever practicable, between the young person and their family.', 61637600, '57 Hicks Street, Red Hill ACT 2603', -35.339146, 149.129462, 'info@catholiccare.cg.org.au', 'Not listed', 0, 0, 0, 1, 0, 0, 1, 'Woden', null, 'Anyone', null, 12, 18, 'No fee', null, 'https://catholiccare.cg.org.au/'),
		(33, 'EveryMan Australia', 'Domestic and family violence prevention services, crisis and longer-term counselling, information and referral, accommodation support, case management and outreach services.
Specialist services for men living with high and complex needs involving the criminal justice system, domestic violence, disability, mental illness, drug and alcohol issues. Accommodation and support services for Indigenous families and individuals at risk of homelessness.
Counselling by appointment; out of hours appointments available. Crisis support available by phone or in office during business hours only.
Violence prevention support through Working With the Man behaviour change program (now open to any person requesting support for any domestic or family violence matters).  ''Preventing Violence, Managing Anger'' 10-week evening group programs available. Initial applicant interview required before place may be offered.', 62306999, 'Room 3.01, Griffin Centre, Genge St, Canberra ACT 2601', -35.276723, 149.132352, 'Not listed', 'Monday to Friday, 9AM to 5PM', 1, 0, 0, 0, 0, 1, 1, 'Civic', 'Wheelchair Access, Toilets', 'Anyone', 'Contact us for details', null, null, 'No fee', null, 'https://www.everyman.org.au/'),
		(34, 'Ainslie Village', 'As a certified housing provider with 30 year’s experience, Argyle makes securing accommodation and sustaining a tenancy, easy and stress free. Equipped with a skilled team of staff, we have the expertise and the resources to help you find and maintain the right rental property for your needs.', 61626800, '23 Quick St, Campbell ACT 2612', -35.274402, 149.147111, 'ainslievillage@argylehousing.com.au', 'Monday to Friday, 9:30AM to 4:30PM', 1, 0, 0, 0, 0, 1, 0, 'Civic', 'Ramp', 'Anyone', null, null, null, 'Contact us for details', null, 'https://argylehousing.com.au/social/ainslie-village/'),
		(35, 'AngliCare Community Lunch', 'Join us for a free Community Lunch on the first and third Wednesday of the month from 12.30 - 1.30pm, hosted by Lanyon Valley Anglican Church (LVAC) staff and volunteers. 
For more information contact office@lvac.org.au or call the LVAC Office on 02 6294 9756
Bring a friend or family member or come to meet new people!', 62949756, 'Gordon Community Centre, 110 Lewis Luxton Avenue, Gordon ACT 2906', -35.449862, 149.084125, 'gordon@anglicare.com.au', 'First and third Wednesday of the month, 12:30PM to 1:30PM', 0, 1, 0, 1, 0, 0, 0, 'Tuggeranong', 'Parking, Disabled Toilet, Ramp to main entrance', 'Anyone', null, null, null, 'No fee', null, 'https://www.anglicare.com.au/services/mission-community-engagement/survive-and-thrive/gordon/'),
		(36, 'Lanyon Pantry ', 'Individuals and families can access emergency assistance with food and other essentials at the Gordon Community Centre. 
Drop in (no appointment required) during our opening hours and speak to one of our friendly volunteers or staff members. All welcome, you will be greeted on your arrival and have a brief, confidential chat about your circumstances to see how we can help you best. There is a safe place for children to play.
We can help with non-perishable food, household and personal essentials, and fresh food when available. We can also help put you in touch with relevant services.', 62847003, 'Gordon Community Centre, 110 Lewis Luxton Avenue, Gordon ACT 2906', -35.449862, 149.084125, 'gordon@anglicare.com.au', 'Tuesday, Wednesday and Friday, 10AM to 1PM and 2PM to 4PM', 0, 1, 0, 0, 0, 0, 0, 'Tuggeranong', 'Parking, Disabled Toilet, Ramp to main entrance', 'Anyone', null, null, null, 'No fee', null, 'https://welovelanyon.com/pantry'),
		(37, 'CatholicCare - Minosa House', 'MINOSA House is a short term crisis accommodation Service funded through the Community Services Directorate of the ACT.  It provides supported accommodation for up to 3 months to single men aged over 18 years who are homeless or at risk of homelessness. Residents engage in Case Management support to assist them to identify and overcome barriers that prevent them from achieving stable accommodation.', 61637600,'57 Hicks Street, Red Hill ACT 2603', -35.339015, 149.129462, 'HSS@catholiccare.cg.org.au', 'Not listed', 1, 0, 0, 0, 0, 0, 0, 'Tuggeranong', null,'Approved service users, Male only', 'State/ Territory Government', 18, null, 'Contact us for details', null, 'https://catholiccare.cg.org.au/services/1159/'),
		(38, 'Orange Sky Laundry', 'Orange Sky Australia is helping to positively connect people experiencing homelessness through free laundry, showers and conversation.', 0408760536, 'Canberra ACT 2601', -35.281162, 149.129714, 'Not listed', 'Not listed', 0, 0, 0, 0, 0, 0, 1, 'Civic', null, null, null, null, null, null, null, 'https://orangesky.org.au/where-we-are/canberra/'),
		(39, 'Aleta Outreach Program', 'Outreach support for single women who are homeless, at risk of homelessness, or who have recently become housed. Outreach can be for up to three months. Provides assistance to maintain a tenancy (private, public, or community), budgeting support and advocacy and referral.', 61227000, 'Canberra ACT 2601', -35.281162, 149.129714, 'TooraAdmin@toora.org.au', 'Monday to Friday 9AM to 5PM', 1, 0, 0, 0, 0, 1, 0, 'Civic', 'Parking, Toilets, Lift', 'Anyone, Female Only', null, null, null, 'No fee', null, 'https://www.toora.org.au/our-services/homelessness-services/outreach-programs-hs/'),
		(40, 'Canberra Youth Residential Service', 'Provides crisis accommodation with 24 hour staffing. Offers advice and referral. For ages 16-25 who are homeless.', 62470330, 'Ainslie ACT 2602', -35.261248, 149.147802, 'None Provided', 'Not listed', 1, 0, 0, 0, 0, 0, 0, 'Civic', 'Wheelchair Access, Ramps, Toilets', 'Approved service users', null, 16, 25, 'Contact us for details', null, 'https://www.communityservices.act.gov.au/hcs/services/youth_housing'),
		(41, 'Street To Home (Saint Vincent De Paul)', 'Provides active outreach to rough sleepers who do not engage with mainstream services and so remain homeless. Offers flexible case management in an assertive outreach model, assisting chronically homeless individuals, with a focus on health, housing and legal issues.', 62822722, 'Deakin ACT 2600', -35.319376, 149.101047, 'info@svdp-cg.org.au', 'Monday to Friday 9AM to 5PM', 1, 0, 0, 1, 0, 0, 1, 'Woden', null, 'Anyone', null, null, null, 'No fee', null, 'https://www.vinnies.org.au/page/Find_Help/ACT/Housing/Street_to_Home/'),
		(42, 'Young Parents Program (Saint Vincent De Paul)', 'Outreach support and accommodation for young families who are homeless or at risk of homelessness. Assists people aged 16-25yrs, who are pregnant or with at least one child in majority care, through the provision of case management. The focus is on the development of life skills and positive parenting skills with an emphasis on family bonding and attachment.', 62347376, 'Deakin ACT 2600', -35.319376, 149.101047, 'info@svdp-cg.org.au', 'Monday to Frdiay 9AM to 5PM', 0, 0, 0, 1, 0, 0, 1, 'Woden', null, 'Anyone', 'Self Referral', 16, 25, 'No fee', null, 'https://www.vinnies.org.au/page/Find_Help/ACT/Health_and_wellbeing/Young_Parents_Program/'),
		(43, 'Samaritan House (Saint Vincent De Paul)', 'Provides crisis accommodation and assistance to men over the age of 18.
Referral: Through One Link
Fees: Fees Apply', 62347307, 'Hackett ACT 2602', -35.246607, 149.163612, 'samhouse@svdp-cg.org.au', 'Open 24/7', 1, 0, 0, 0, 0, 0, 0, 'Civic', 'Ramp, Toilets', 'Anyone, Male only', 'Self Referral ', 18, null, 'Contact us for details', null, 'https://www.vinnies.org.au/page/Find_Help/ACT/Housing/Samaritan_House/'),
		(44, 'Night Patrol ( Saint Vincent De Paul)', 'Night Patrol provides mobile outreach offering refreshments and friendly faces to people on the streets every night of the year. The Night Patrol teams are made up of enthusiastic and compassionate volunteers from within the community who receive specialised training to help support those in need. Referrals to our community services are available through Night Patrol.', 62822722, 'PO Box 51, Deakin West ACT 2600', -35.317388, 149.097659, 'night.patrol@svdp-cg.org.au', '1) Van 1
Mondays: Cube area in Civic at approx. 7.30pm, City Walk in Garema Place at approx. 8.00pm
Tuesdays: Cube area in Civic approx. 7.30pm, City Walk in Garema Place at approx. 8.20pm
Wednesdays: Cube area in Civic at approx. 7.30pm, City Walk in Garema Place at approx. 8.00pm
Thursdays: Dickson Pl, Dickson Library at approx. 7.00pm, City Walk in Garema Place at approx. 8.00pm
Fridays: Dickson Pl, Dickson Library at approx. 8.00pm, City Walk in Garema Place at approx. 9.00pm 
Saturdays: Cube area in Civic at approx. 8.00pm, Dickson Pl, Dickson Library at approx.8.45pm, City Walk in Garema Place at approx. 9.30pm
Sundays: Cube area in Civic at approx. 7.30pm, City Walk in Garema Place at approx. 8.00pm
2) Van 2
Mondays: Dickson Pl, Dickson Library at approx. 7.30pm
Tuesdays: Queanbeyan Visitors Information Centre, Farrer Pl at approx. 7.30pm, Corner of Bradley & Neptune St Woden at approx. 8.15pm
Wednesdays: Queanbeyan Visitors Information Centre, Farrer Pl at approx. 7.30pm, Corner of Bradley & Neptune St Woden at approx. 8.15pm
Thursdays: Queanbeyan Visitors Information Centre, Farrer Pl at approx. 7.30pm, Corner of Bradley & Neptune St Woden at approx. 8.15pm
Fridays: Queanbeyan Visitors Information Centre, Farrer Pl at approx. 7.30pm, Corner of Bradley & Neptune St Woden at approx. 8.15pm 
Saturdays: Queanbeyan Visitors Information Centre, Farrer Pl at approx. 7.30pm, Corner of Bradley & Neptune St Woden at approx. 8.15pm
Sundays: Dickson Pl, Dickson Library at approx. 7.30pm', 0, 0, 0, 0, 0, 0, 1, 'Woden', null, 'Anyone', null, null, null, 'No fee', null, 'https://www.vinnies.org.au/page/Find_Help/NSW/Food/Sydney_Night_Patrol/'),
		(45, 'Lesly''s Place (Toora Women''s Inc)', 'Provides support for women from 16yrs with drug and alcohol issues. Offers outreach support for women in the community who are in recovery or who have a desire to change their drug and alcohol use. Offers a short term service up to three months for women and any accompanying children who need support in early recovery. Also runs a halfway house for women and any accompanying children with established recovery who are homeless. 8 week day program offering alcohol and other drug relapse prevention information, education and skill building based on social cognitive behavioural model.', 62417233, 'Jamison Centre ACT 2614', -35.253079, 149.071059, 'TooraAdmin@toora.org.au', 'Monday to Friday 9AM to 5PM', 1, 0, 0, 0, 0, 0, 1, 'Belconnen', 'Wheelchair Access', 'Anyone, Female Only', null, 16, null, 'Contact us for details', null, 'https://www.toora.org.au/our-services/alcohol-and-other-drugs-services/residential-health-treatment-programs/'),
		(46, 'Toora Womens Incorporated', 'Provides shared accommodation for single women unaccompanied by children who are homeless for a variety of reasons such as mental health, alcohol and drug issues, financial difficulties, and trauma.
Referral: One Link
Fees: Fees Apply', 61227000, 'Canberra ACT 2601', -35.279831, 149.127826, 'TooraAdmin@toora.org.au', 'Monday to Friday 9AM to 5PM', 1, 0, 0, 0, 0, 0, 1, 'Civic', 'Wheelchair Access', 'Anyone, Female Only', null, null, null, 'Contact us for details', null, 'https://www.toora.org.au/'),
		(47, 'Beryl Womens Inc - Crisis Accomodation', 'Beryl provides short term, low cost crisis housing to women and their children who are homeless due to domestic violence. Referral: Referrals for accommodation and/or outreach support should be directed to OneLink on 1800 176 468.', 62306900, 'Canberra ACT 2600', -35.301985, 149.115733, 'admin@beryl.org.ai', 'Monday to Frdiay 8:30AM to 5:30PM', 1, 0, 0, 0, 0, 1, 1, 'Civic', 'Toilets, Hearing Loop, Wheelchair Access', 'Anyone, Female Only', 'Self Referral', null, null, 'Contact us for details', 'Range of languages available, translating service can be arranged', 'http://www.beryl.org.au/'),
		(48, 'Comnig Home - Toora Womens Inc', 'Provides referral and information for women exiting the correction system. Support available to service providers only. Provides services to women exiting the correction system that reduce homelessness and recidivism.
Practical and emotional support available including accommodation, drug and alcohol, sexual assault and domestic violence support as needed. Outreach and case management available.', 62472399, 'Canberra ACT 2601', -35.281723, 149.127397, 'TooraAdmin@toora.org.au', 'Monday to Friday 9AM to 5PM', 1, 0, 1, 1, 0, 1, 1, 'Civic', null, 'Anyone, Female Only', null, null, null, 'No fee', null, 'https://www.toora.org.au/'),
		(49, 'Legal Aid ACT', 'Provides free legal information, referral and limited advice to anyone in the ACT. Can assist with most legal issues including family separation, tenants and landlords, employment, neighbourhood disputes and wills.
Referral: Phone the Helpline or attend at our office', 1300654314, '2 Allsop Street, Canberra ACT 2601', -35.278446, 149.124825, 'legalaid@legalaidact.org.au', 'Monday to Friday 8:30AM to 5PM', 0, 0, 0, 1, 1, 0, 0, 'Civic', 'Wheelchair Access, Disabled Toiletss', null, null, null, null, null, null, 'http://www.legalaidact.org.au/'),
		(50, 'Care Financial Services ', 'Provides qualified financial counsellors for people on moderate to low incomes experiencing financial problems. Offers financial counselling on issues underlying and directly linked to financial well being.
Offers no-interest loans. After hours drop-in service 5:30-7:30pm Wednesdays.
Provides legal assistance and advice to low or moderate income consumers, primarily in the areas of consumer credit, telecommunications and utilities, also general fair trading and consumer protection.
Telephone Information Service 9am-4:30pm weekdays. Weekday appointments by arrangement.', 1800007007, '1st Floor Waldorf Apartments, 2 Akuna Street, Canberra ACT 2601', -35.281816, 149.132513, 'admin@carefcs.org', 'Monday to Friday 9AM to 5PM', 0, 0, 0, 0, 1, 0, 0, 'Civic', null, 'Anyone', null, null, null, 'No fee', null, 'http://www.carefcs.org/'),
		(51, 'Emergency Financial and material aid', 'UnitingCare Kippax can help. Our experienced and qualified counsellors can assist with things like food hampers, gift cards to purchase fresh food, support with medical and pharmaceutical bills and bus tickets, help with housing and legal aid, and financial counselling. In winter we can assist with warm clothing and bedding.
Emergency financial and material aid is offered to all who live in Canberra and surrounding areas.
We also co-ordinate the Canberra-wide Christmas Gift Appeal & Teenage Gift appeal for families living in disadvantage and poverty.', 62541733, 'Corner Luke Street and Hardwick Crescent, Holt ACT 2615', -35.222235, 149.01879, 'info@kippax.org.au', 'None listed', 0, 0, 0, 0, 1, 0, 0, 'Belconnen', 'Parking, Ramps', 'Anyone', null, null, null, null, null, 'https://kippax.org.au/'),
		(52, 'Youth Employment Pathways Hub', 'The Youth Employment Pathways Hub offers one-on-one, tailored employment support to young people aged 17-25 years living in or accessing the Belconnen area. 
Young people meet with youth workers to create an Employment Pathways Plan.  The plan outlines the young people’s employment goals and the type of support they would like to meet those goals. The plan can include language, literacy and life skills, as well as training, volunteering and work experience opportunities. 
The Youth Employment Pathways Hub operates via appointment on Mondays and Wednesdays, 1pm-4pm from Belconnen Youth Centre, located on the Corner of Chandler St and Swanson Court, Belconnen.
The Youth Employment Pathways Program includes partnerships with Riverview Projects ACTand Canberra Institute of Technology, to provide suitable participants with work experience and vocational training at Certificate II and III levels.', 62640200, 'Corner of Chandler Street and Swanson Court, Belconnen ACT 2616', -35.238983, 149.070393, 'bcs@bcsact.com.au', 'Mondays and Wednesdays, 1PM to 4PM', 0, 0, 1, 0, 0, 0, 0, 'Belconnen', 'Wheelchair Access', 'Anyone', null, 17, 25, 'No fee', null, 'https://www.bcsact.com.au/programs-and-services/youth-employment/'),
		(53, 'Property Plus Group ', 'Contracts are held in both government and private sectors with all profits coming back to Oasis.
The programs aim is to develop a positive work ethic and provide young people with opportunities to develop life skills and competencies needed to secure on-going employment in the greater workplace.
The program started in 2003 under the name of Oasis Social Enterprise Initiatives (OSEI) and was originally developed in partnership with NEW Housing to provide cleaning and gardening services for the Department’s inner city housing stock.', 62920894, '7B Hester Place, Chisholm ACT 2905', -35.420029, 149.12881, 'None Provided', 'None Provided', 0, 0, 1, 0, 0, 0, 0, 'Tuggeranong', null, null, null, null, null, 'No fee', null, 'https://www.salvationarmy.org.au/oasis/services/training/property-plus-group/'),
		(54, 'Centrelink/Medicare Belconnen', 'Offers a range of programs, services and payments in government and social areas including unemployment benefits.', 132307, 'North Point Plaza
8 Chandler Street
Belconnen ACT 2617', -35.237758, 149.068865, 'centrelink@humanservices.gov.au', 'Monday to Friday, 8:30AM to 4:30PM', 0, 0, 1, 1, 0, 1, 1, 'Belconnen', 'Parking', 'Anyone', null, null, null, 'No fee', 'For languages other than English call 13 12 02', 'https://findus.humanservices.gov.au/findnearest.asp?locationid=535667&submittopage=locatorprofile.asp'),
		(55, 'Centrelink/Medicare Woden', 'Offers a range of programs, services and payments in government and social areas including unemployment benefits.', 132307, '2-6 Bowes Street
Woden ACT 2606', -35.341723, 149.085639, 'centrelink@humanservices.gov.au', 'Monday to Friday, 8:30AM to 4:30PM', 0, 0, 1, 1, 0, 1, 1, 'Woden', 'Parking', 'Anyone', null, null, null, 'No fee', 'For languages other than English call 13 12 02', 'https://findus.humanservices.gov.au/findnearest.asp?locationid=535671&submittopage=locatorprofile.asp'),
		(56, 'Centrelink/Medicare Gungahlin', 'Offers a range of programs, services and payments in government and social areas including unemployment benefits.', 132307, 'The Marketplace Gungahlin
30 Hibberson Street
Gungahlin ACT 2912', -35.185274, 149.134368, 'centrelink@humanservices.gov.au', 'Monday to Friday, 8:30AM to 4:30PM', 0, 0, 1, 1, 0, 1, 1, 'Gungahlin', 'Parking', 'Anyone', null, null, null, 'No fee ', 'For languages other than English call 13 12 02', 'https://findus.humanservices.gov.au/findnearest.asp?locationid=535669&submittopage=locatorprofile.asp'),
		(57, 'Centrelink/Medicare Braddon', 'Offers a range of programs, services and payments in government and social areas including unemployment benefits.', 132307, '13 Lonsdale Street
Braddon ACT 2612', -35.273963, 149.132565, 'centrelink@humanservices.gov.au', 'Monday to Friday, 8:30AM to 4:30PM', 0, 0, 1, 1, 0, 1, 1, 'Civic', 'Parking', 'Anyone', null, null, null, 'No fee', 'For languages other than English call 13 12 02', 'https://findus.humanservices.gov.au/findnearest.asp?locationid=535668&submittopage=locatorprofile.asp'),
		(58, 'Centrelink/Medicare Tuggeranong', 'Offers a range of programs, services and payments in government and social areas including unemployment benefits.', 132307, 'Cnr Anketell Street & Reed Street South
Tuggeranong ACT 2900', -35.418912, 149.070288, 'centrelink@humanservices.gov.au', 'Monday to Friday, 8:30AM to 4:30PM', 0, 0, 1, 1, 0, 1, 1, 'Tuggeranong', 'Parking', 'Anyone', null, null, null, 'No fee', 'For languages other than English call 13 12 02', 'https://findus.humanservices.gov.au/findnearest.asp?locationid=535670&submittopage=locatorprofile.asp'),
		(59, 'Anger Management Program', 'The ‘Defusing Family Violence: Face Your Anger’ anger management program for young people aged 12-18 years who are struggling to manage their emotions.
Participants of these programs address the topic in a group environment supported by their peers. This program runs throughout the year and referrals are accepted at all times.
Participants are placed in groups appropriate to their age and maturity level. Canberra PCYC facilitates the ''Face Your Anger'' program for participants from across the ACT, with convenient transport options available for Northside and Southside participants.
Funding for the ''Face Your Anger'' program is provided by ACT Policing.
Outcomes include:
A reduction in family violence and violent behaviours
Strategies for dealing with challenging situations
Improved communication techniques
Improvement in family relationships', 62967822, '17 Grattan Court, Wanniassa ACT 2903', -35.402333, 149.098126, 'referral@pcyc.net.au', 'None Provided', 0, 0, 0, 1, 0, 0, 0, 'Tuggeranong', 'Parking, Toilets', 'Anyone', 'Contact us for details', null, null, null, null, 'https://www.pcyc.net.au/anger-management/'),
		(60, 'Mary Mead ARCK program', 'Marymead''s ARCK Program supports and assists separated parents who are in high conflict over post-separation parenting of their children. ARCK focuses on reducing conflict between parents and assists them in maintaining a positive relationship with their children and a working relationship with the other parent.
ARCK is for separated parents and their children who are experiencing:
High levels of ongoing conflict
Difficulties in communicating with the other parent
Concerns regarding their child''s wellbeing
Concerns regarding trust and safety
Involvement with the Family Court or Magistrates Court', 1800427920, 'Rheinberger Centre, Corner Weston and Loch Streets, Yarralumla ACT 2600', -35.30977, 149.104173, 'programs@marymead.org.au', 'Monday to Friday 9AM to 5PM', 0, 0, 0, 1, 0, 0, 0, 'Woden', 'Parking', 'Anyone', null, null, null, 'Contact us for details', null, 'http://www.marymead.org.au/services/assisting-responsible-care-for-kids-arck'),
		(61, 'Narrabundah House', 'Supported accommodation for Indigenous males 15-18yrs of age.', 132281, 'Canberra ACT 2601', -35.281653, 149.128341, 'CSD@act.gov.au', 'None listed', 1, 0, 0, 0, 0, 1, 0, 'Woden', null, null, null, null, null, null, null, 'https://www.accesscanberra.act.gov.au/app/answers/detail/a_id/163/~/narrabundah-house-indigenous-supported-residential-facility-%28bimberi'),
		(62, 'Family Therapy - Strategic Psychology', 'Navigating family dynamics can become difficult due to competing needs, existing alliances and communication difficulties. At Strategic Psychology, family therapy involves working with the entire family to address some of the issues identified as contributing to a less than ideal family dynamic. Family therapy resolves conflicts in a healthier way, fostering enriching family relationships. It works to help individuals understand each other and create stronger bonds to manage conflict in a healthy and productive way for all family members.
Family therapy can be useful for all types of families experiencing conflict. From traditional nuclear families, to blended families, single parent families and same-sex marriage families, families with young children or families with adult children. Our friendly, trained psychologists will approach your family with neutrality and respect, to gain an understanding of the difficulties you are facing within the family unit. We will work with you to assist in identifying issues, the effect these are having on family dynamics and work collaboratively with all family members to assist in finding better ways to cope.
Strategic Psychology In Canberra
In some cases, individuals within the family will be engaged with individual counselling services to assist with addressing their own challenges and difficulties. This can also be provided at our private practice in Canberra with another of our psychologists.
For children with disorders such as ADHD, autism or learning difficulties, we also have trained child psychologists at Strategic Psychology. Please contact us for more information on 02 6108 3432.', 62626157,'Lvl 1, Suite 2, 99 London Cct, Canberra City ACT 2601', -35.279265, 149.129611,'support@strategicpsychology.com.au', 'None Listed', 0, 0, 0, 1, 0, 0, 1, 'Civic', null, 'Anyone', null, null, null, 'Contact us for details', null, 'https://strategicpsychology.com.au/services/family-therapy/')
) 
AS Source (ServiceID, Name, Description, Phone, Address, Longitude, Latitude, Email, OpeningHours, Shelter, Food, Job, Family, Legal, Diversity, Health, Location, Accessability, Clientele, Referral, MinAge, MaxAge, Cost, Languages, Website) 
ON Target.ServiceID = Source.ServiceID 
WHEN NOT MATCHED BY TARGET THEN 
INSERT (Name, Description, Phone, Address, Longitude, Latitude, Email, OpeningHours, Shelter, Food, Job, Family, Legal, Diversity, Health, Location, Accessability, Clientele, Referral, MinAge, MaxAge, Cost, Languages, Website) 
VALUES (Name, Description, Phone, Address, Longitude, Latitude, Email, OpeningHours, Shelter, Food, Job, Family, Legal, Diversity, Health, Location, Accessability, Clientele, Referral, MinAge, MaxAge, Cost, Languages, Website);
