CREATE TABLE [dbo].[Service]
(
	[ServiceID] INT IDENTITY (1, 1) NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
	[Phone] CHAR(10) NULL, 
	[Address] NVARCHAR(MAX) NULL,
	[Longitude] DECIMAL(9, 6) NOT NULL, 
    [Latitude] DECIMAL(9, 6) NOT NULL, 
	[Email] VARCHAR(320) NULL, 
	[OpeningHours] NVARCHAR(MAX) NULL, 
    [Shelter] BIT NOT NULL,     
    [Food] BIT NOT NULL, 
	[Job] BIT NOT NULL, 
	[Family] BIT NOT NULL,
    [Legal] BIT NOT NULL, 
    [Diversity] BIT NOT NULL, 
	[Health] BIT NOT NULL,
	[Location] CHAR(10) NOT NULL, 
    [Accessability] VARCHAR(200) NULL, 
    [Clientele] VARCHAR(200) NULL, 
    [Referral] VARCHAR(200) NULL, 
	[MinAge] INT NULL, 
    [MaxAge] INT NULL, 
	[Cost] VARCHAR(50) NULL, 
    [Languages] VARCHAR(MAX) NULL, 
    [Website] VARCHAR(2083) NULL, 
    PRIMARY KEY CLUSTERED ([ServiceID] ASC)
)
