//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTYouthServicesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Shelter { get; set; }
        public Nullable<bool> Health { get; set; }
        public Nullable<bool> Food { get; set; }
        public Nullable<bool> Legal { get; set; }
        public Nullable<bool> Family { get; set; }
    }
}
